openapi: 3.0.3
info:
  title: WASAtext
  description:  |
    This API allow multiple users to chat with each other,
    one-to-one or by creating group chat, an user can start
    new conversation by searching other user, or add them to
    an existing chat to create a group.
  version: 0.2.1fray

servers:
  - url: http://localhost:3000
    description: Local development server

tags:
  - name: Login 
    description: Operations relative to the login of the user
  
  - name: User operation
    description: Operations relative to the user, such as change or get name/propic, ecc
  
  - name: Chat operation
    description: Operations relative to the chat, such retrive the user's chat, retrive a chat name, ecc
  
  - name: Group chat operation
    description: Operations relative to the group chat
  
  - name: Message operation
    description: Operations relative to the messages, such as send a message, change the status to read message, delete it, ecc


components:
  parameters:
    usr_id:
      description:  |
        Unique user id
      
      schema:
        $ref: "#/components/schemas/User/properties/usrId"
      name: usr_id
      in: path
      required: true
      
    chat_id:
      description:  |
        Unique chat id
      
      schema:
        $ref: "#/components/schemas/Chat/properties/chatId"
      name: chat_id
      in: path
      required: true
    
    msg_id:
      description: |
        Unique message id
      
      schema:
        $ref: "#/components/schemas/Message/properties/msgId"
      name: msg_id
      in: path
      required: true
    

  schemas:
    User:
      description:  |
        Contain information about an user of the app,
        such as its name, user id, and profile photo.
      
      type: object
      title: User

      properties:
        usrId:
          description:  |
            Unique user id
      
          type: string
          pattern: '^[^\s].*[^\s]$'
          example: "ofnarc754"
          
          minLength: 3
          maxLength: 32
          readOnly: true
        
        userName:
          description:  |
            Username
          
          type: string
          pattern: '^[^\s].*[^\s]$'
          example: "franco"
          
          minLength: 3
          maxLength: 16
        
        userPhoto:
          description:  |
            User profile photo (propic) encoded in base64
          
          type: string
          format: binary
          example: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
          
          minLength: 0
          maxLength: 1398101 #Equivalente di 1MB di dati binari in base64
    
    Chat:
      description:  |
        Contain information about a chat of two or more users,
        such as the name of the chat, the propic the participants
        and the id.

      type: object
      title: Chat
      
      properties:
        chatId:
          description:  |
            Unique chat id
          
          type: integer
          
          minimum: 0
          maximum: 999
          readOnly: true

        chatName:
          description:  |
            Chat name, if it's a one-to-one chat the name
            correspond to the other username
          
          type: string
          pattern: '^[^\s].*[^\s]$'
          example: "Chat Uni"
          
          minLength: 3
          maxLength: 16

        chatPhoto:
          description:  |
            Chat Photo, if it's a one-to-one chat is the propic of the other user,
            else contain the group photo
          
          type: string
          format: binary
          example: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."

          minLength: 0
          maxLength: 1398101

        isGroup:
          description:  |
            Used to distinguish group chat between one-to-one chat_id.
            false: one-to-one chat with only 2 users
            true: chat with more than 2 users
            
          type: boolean

        participants:
          description:  |
            Array containing the users id of the users in the chat
          
          type: array
          minItems: 2
          maxItems: 64
          items:
            $ref: "#/components/schemas/User"

    Message:
      description:  |
        Contain the message content, and other parameter such as:<br>
        msg_id, senderId, contentType(if a photo or a text message),
        message_content, delivery status, comment and like/dislike
      
      type: object
      title: Message
      
      properties:
        msgId:
          description:  |
            Unique message id
          
          type: integer
          minimum: 0
          maximum: 999
          readOnly: true
        
        senderId:
          description:  |
            Correspond to the usr_id of the user that sended the message
          
          type: string
          pattern: '^[^\s].*[^\s]$'
          example: "ofnarc754"

          minLength: 3
          maxLength: 32
          readOnly: true

        respondTo:
          description:  |
            If the message is in response of another message, this field
            corresponds of the id of that messages, the message is not
            responding to other messages if this field have -1

          type: integer
          minimum: -1
          maximum: 1000

        textContent:
          description:  |
            Contain the text content of the message
          
          type: string
          pattern: '^(?!\s*$).+'
          example: "Ciao franco, come stai?"

          minLength: 1
          maxLength: 1024

        photoContent:
          description:  |
            Photo content

          type: string
          format: binary
          pattern: '^.*$'
          example: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
              
          minLength: 0
          maxLength: 2787949
        
        deliveryStatus:
          description:  |
            Enum string used for set the status of a message:<br>
              - sent: the receiver user isn't connected to the app<br>
              - received: the user received the message but he didn't read it<br>
              - read: read by the user
          
          type: string
          enum:
            - sent
            - received
            - read

        timestamp:
          description:  |
            Define the time of when the message was sent
          
          type: string
          format: date-time
          example: "2021-06-01T14:10:27Z"

          minLength: 18
          maxLength: 22
        
        comments:
          description:  |
            Array of comments/reaction of a message,
            a message can have maximum 16 comments
          
          type: array
          minItems: 0
          maxItems: 16
          items:
            $ref: "#/components/schemas/Comment"
    
    Comment:
      description:  |
        Schema for the comment (reaction with emoji) section of a message
        it have the content of the comment (one emoji) the user who leaved the
        comment and a comment id that its connected to the message

      type: object
      title: Comment

      properties:
        commentId:
          description: |
            Id of the comment

          type: integer
          minimum: 0
          maximum: 1000

        commenterId:
          description:  |
            Comment id of the user who commented the message

          type: string
          pattern: '^[^\s].*[^\s]$'
          example: "ofnarc754"

          minLength: 3
          maxLength: 32
          readOnly: true

        content:
          description:  |
            Content of the comment, it's an emoji in utf-8
          
          type: string
          pattern: '^.*$'
          example: "😀"

          minLength: 1
          maxLength: 1

    Error:
      description: Personalizable error
      type: object
      properties:
        content:
          description: Short description of the error

          type: string
          pattern: "^.*$"

          minLength: 3
          maxLength: 40
          example: "token expired"

        code:
          description: Error code

          type: string
          pattern: "^[A-Z0-9 ]+$"

          minLength: 3
          maxLength: 20
          example: "TOKEN NOT VALID"

  responses:
    UnauthorizedError:
      description: Unauthorized - Authentication required or failed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    InternalError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    BadRequestError:
      description: Bad request - requestBody not valid or empty
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    OperationNotAllowed:
      description: Forbidden - the operation is not allowed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    NotFoundError:
      description: Not found - the content requested was not found in the database
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  securitySchemes:
    BearerAuth:
      description:  |
        Define the security scheme for the api, in this case it's used Bearer Token,<br>
        and the token correspond to the usr_id
      type: http
      scheme: bearer
      bearerFormat: plain

paths:
  /session:                                                       #Endpoint per il login
    post:
      description:  |
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      summary: Logs in the user

      tags: ["Login"]
      operationId: doLogin

      requestBody:
        description: Username required for loggin in
        required: true
        content:
          application/json:
            schema:
              description:  |
                Request the name of the user
              type: object
              properties:
                userName:
                  $ref: "#/components/schemas/User/properties/userName"

            example:
              userName: "franco"

      responses:
        "201":
          description:  |
            User sign-in action successful, the user wasn't in the
            db, so it was the first time login
          content:
            application/json:
              schema:
                description:  |
                    Response with the user info

                type: object
                properties:
                  user: 
                    $ref: "#/components/schemas/User"
              
              example:
                user:
                  usr_id: "franco245"
                  userName: "franco"
                  userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."

        "400":
          $ref: "#/components/responses/BadRequestError"

        "500":
          $ref: "#/components/responses/InternalError"

  #-----------------
  # USER ENDPOINTS
  #-----------------

  /users:                                                         #Endpoint degli utenti dell'app
    get:
      description:  |
        Consent to show all the users of the WASAtext, useful when an user
        want to start a new conversation, or add another user to a group
      summary: List all users

      tags: ["User operation"]
      operationId: getUsers

      security:
        - BearerAuth: []
      
      responses:
        "200":
          description: Show an array that contain all the users of the WASAText
          content:
            application/json:
              schema:
                description:  |
                  Array of users
                
                type: object
                properties:
                  users:
                    description:  |
                      Array of all the users of the app
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
                    
                    minItems: 0
                    maxItems: 256
          
              example:
                users:
                  - usr_id: "franco245"
                    userName: "franco"
                    userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                  - usr_id: "maria34"
                    userName: "maria"
                    userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."

        "401":
         $ref: "#/components/responses/UnauthorizedError"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"
  
  /users/{usr_id}:                                                #Endpoint di un utente
    parameters:
      - $ref: "#/components/parameters/usr_id"
    
    get:
      description:  |
        Retrive the photo and name of an user by its usr_id,
        useful for when an user want se info of other user in
        a chat or group
      summary: Get user info

      tags: ["User operation"]
      operationId: getUserInfo

      security:
        - BearerAuth: []
      
      responses:
        "200":
          description:  |
            Information retrived successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              
              example:
                usrId: "ofnarc754"
                userName: "franco"
                userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
        
        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

  /profile:
    put:
      description:  |
        Update only the username leaving invariated the id and photo
      summary: Change the username
      
      tags: ["User operation"]
      operationId: setMyUserName

      security:
        - BearerAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              description:  |
                The request body expects to receive the userName field compatible
                with the one described in the user schema 
              
              type: object
              properties:
                newUserName:
                  $ref: "#/components/schemas/User/properties/userName"
      
      responses:
        "202":
          description: Username updated successfully
          content:
            application/json:
              schema:
                description:  |
                  Return the username updated
                
                type: object
                properties:
                  userName:
                    $ref: "#/components/schemas/User/properties/userName"
              
              example:
                userName: "francofronco"

        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"
  
  /profile/propic:                                         #Enpoint per la propic di un utente
    put:
      description:  |
        Update only the photo leaving invariated the id and the name
      summary: Change the propic

      tags: ["User operation"]
      operationId: setMyPhoto
      
      security:
        - BearerAuth: []
      
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              description:  |
                The request body expects to receive the photo field compatible
                with the one described in the user schema 
              
              type: object
              properties:
                newUserPhoto:
                  $ref: "#/components/schemas/User/properties/userPhoto"
      
      responses:
        "202":
          description: Photo updated successfully
          content:
            application/json:
              schema:
                description:  |
                  Return the propic updated
                
                type: object
                properties:
                  userPhoto:
                    $ref: "#/components/schemas/User/properties/userPhoto"
              
              example:
                userPhoto: "iVBORw0KGgoAAAANSUhUEgAUAAAA..."
        
        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"
  
  #-----------------
  # CHAT ENDPOINTS
  #-----------------

  /chats:                                                         #Endpoint delle chat
    get:
      description:  |
        Return an array that contain all the chats, with the last message for the chats
      summary: List the chats of the user
      
      tags: ["Chat operation"]
      operationId: getMyConversations

      security:
        - BearerAuth: []

      responses:
        "200":
          description:  |
            The response contain a json object composed by an array with all(32 for now) the user chat
          content:
            application/json:
              schema:
                description: List with all the chats of the user.

                type: object
                properties:
                  chats:
                    description:  |
                      Array of chats
                    type: array
                    minItems: 0
                    maxItems: 1000
                    items:
                      $ref: "#/components/schemas/Chat"
              
              example:
                chats:
                  - chat_id: 234
                    chatName: "Chat Uni"
                    chatPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                    isGroup: true
                    participants:
                      - usr_id: "franco245"
                        userName: "franco"
                        userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                      - usr_id: "maria34"
                        userName: "maria"
                        userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                  - chat_id: 254
                    chatName: "Roberto"
                    chatPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                    isGroup: false
                    participants:
                    - usr_id: "franco245"
                      userName: "franco"
                      userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                    - usr_id: "maria34"
                      userName: "maria"
                      userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

    post:
      description:  |
        Consent the user to start a new chat with one or more user/s,
        the body need to have a message (the chat need to have at least 1 message)
      summary: Start new chat

      tags: ["Chat operation"]
      operationId: startNewChat

      security:
        - BearerAuth: []

      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              description:  |
                The request body expect to retrieve the chat type, (name and photo if it's a group
                if isn't a group they can be empty) the participants of the future chat and the
                first message

              type: object
              properties:
                chatName:
                  $ref: "#/components/schemas/Chat/properties/chatName"

                chatPhoto:
                  $ref: "#/components/schemas/Chat/properties/chatPhoto"
                
                isGroup:
                  $ref: "#/components/schemas/Chat/properties/isGroup"

                participantsId:
                  $ref: "#/components/schemas/User/properties/usrId"
                

                messageTextContent:
                  $ref: "#/components/schemas/Message/properties/textContent"
                
                messagephotoContent:
                  $ref: "#/components/schemas/Message/properties/photoContent"

      responses:
        "201":
          description: Response with the chat info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat"

              example:
                chat_id: 344
                chatName: "Franco"
                chatPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                isGroup: false
                participants:
                  - usr_id: "franco245"
                    userName: "franco"
                    userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                  - usr_id: "maria34"
                    userName: "maria"
                    userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
        
        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "500":
          $ref: "#/components/responses/InternalError"

  /chats/{chat_id}:                                               #Endpoint di una chat
    parameters:
      - $ref: "#/components/parameters/chat_id"
    
    get:
      description:  |
        Retrive all the info of the chat
      summary: Get chat info

      tags: ["Chat operation"]
      operationId: getChatInfo

      security:
        - BearerAuth: []

      responses:
        "200":
          description: |
            Information retrived successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat"

              example:
                chat_id: 344
                chatName: "Franco"
                chatPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                isGroup: false
                participants:
                  - usr_id: "franco245"
                    userName: "franco"
                    userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                  - usr_id: "maria34"
                    userName: "maria"
                    userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."

        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

    put:
      description:  |
        Change group name
      summary: Change Group name

      tags: ["Group chat operation"]
      operationId: setGroupName

      security:
        - BearerAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              description:  |
                The request body expects to receive the chatName field compatible
                with the one described in the chat schema 

              type: object
              properties:
                newGroupName:
                  $ref: "#/components/schemas/Chat/properties/chatName"

      responses:
        "202":
          description: Group chat name updated successfully
          content:
            application/json:
              schema:
                description:  |
                  Return the updated chat name

                type: object
                properties:
                  chatName:
                    $ref: "#/components/schemas/Chat/properties/chatName"

              example:
                chatName: "Chat belli"

        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"
  

  /chats/{chat_id}/propic:                                        #Endpoint della propic di una chat
    parameters:
      - $ref: "#/components/parameters/chat_id"
    
    put:
      description:  |
        Update only the group chat photo leaving invariated the other properties
      summary: Change the group chat photo

      tags: ["Group chat operation"]
      operationId: setGroupPhoto
      
      security:
        - BearerAuth: []

      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              description:  |
                The request body expects to receive the chatPhoto field compatible
                with the one described in the chat schema 
              
              type: object
              properties:
                newGroupPhoto:
                  $ref: "#/components/schemas/Chat/properties/chatPhoto"
      
      responses:
        "202":
          description: Photo updated successfully
          content:
            application/json:
              schema:
                description:  |
                  Return the updated photo
                type: object
                properties:
                  chatPhoto:
                    $ref: "#/components/schemas/Chat/properties/chatPhoto"
              
              example:
                chatPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
        
        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

  /chats/{chat_id}/users:                                         #Endpoint degli utenti di una chat
    parameters:
      - $ref: "#/components/parameters/chat_id"

    post:
      description:  |
        Add an user to the chat, by inserting the usr_id
        of the user in the array of participants
      summary: Add an user to a group

      tags: ["Group chat operation"]
      operationId: addToGroup

      security:
        - BearerAuth: []
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: |
                usrId of the user to be added to the chat

              type: object
              properties:
                usrId:
                  $ref: "#/components/schemas/User/properties/usrId"

              example:
                usrId: "artmat34"
      
      responses:
        "200":
          description: User added successfully, return the list of participant refreshed
          content:
            application/json:
              schema:
                description:  |
                  List with the participants of the chat included the new added
                
                type: object
                properties:
                  participants:
                    description: Return the participants of the chat renewed

                    type: array
                    items:
                        $ref: "#/components/schemas/User"
              
                    minItems: 1
                    maxItems: 32
              
              example:
                participants:
                  - usr_id: "franco245"
                    userName: "franco"
                    userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                  - usr_id: "maria34"
                    userName: "maria"
                    userPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."

        "204":
          description: No content, user is already in the chat
        
        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

    delete:
      description:  |
        The user leave the chat, so the user is removed from the users of the chat
        and all its message will be removed from the history, the user is idenfied by it's token
      summary: Leave a group chat

      tags: ["Group chat operation"]
      operationId: leaveGroup

      security:
        - BearerAuth: []
      
      responses:
        "204":
          description: User successfully leaved the chat
        
        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"
    
  #-----------------
  # MESSAGE
  #-----------------

  /chats/{chat_id}/messages:                                      #Endpoint dei messaggi di una chat
    parameters:
      - $ref: "#/components/parameters/chat_id"
    
    put:
      description:  |
        Retrive messages of the chat ordered from the newest to the oldest,
        and update it's status to received, starting from a specify msgId
      summary: Get chat messages

      tags: ["Message operation"]
      operationId: getConversation

      security:
        - BearerAuth: []

      requestBody:
        content:
          application/json:
            schema:
              description:  |
                msgId from where starting to receiving new messages

              type: object
              properties:
                msgId:
                  $ref: "#/components/schemas/Message/properties/msgId"
            
            example:
              msgId: 2

      responses:
        "200":
          description:  |
            Messages retrieved successfully
          content:
            application/json:
              schema:
                description:  |
                  Array of messages
                
                type: object
                properties:
                  messages:
                    description:  |
                      chat message maximum 256

                    type: array
                    items:
                      $ref: "#/components/schemas/Message"
                    
                    minItems: 1
                    maxItems: 256
              
              example:
                messages:
                  - msgId: 3
                    senderId: "ofnarc754"
                    textContent: "ga"
                    photoContent: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                    deliveryStatus: "sent"
                    timestamp: "2021-06-01T14:10:27Z"
                    comments:
                      - commenterId: "ofnarc754"
                        content: "😒"
                  - msgId: 345
                    senderId: "ordigro293"
                    textContent: "Ciao franco!!"
                    photoContent: ""
                    deliveryStatus: "read"
                    timestamp: "2021-06-01T16:10:27Z"
                    comments:
                      - commenterId: "ofnarc754"
                        content: "😒"
                  - msgId: 266
                    senderId: "maria34"
                    textContent: "go"
                    photoContent: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
                    deliveryStatus: "read"
                    timestamp: "2021-06-01T18:10:27Z"
                    comments:
                      - commenterId: "ofnarc754"
                        content: "😒"
                      - commenterId: "maria34"
                        content: "😒"
        
        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

    post:
      description:  |
        Send a message in the chat, the user is identified by the auth token.
      summary: Send message

      tags: ["Message operation"]
      operationId: sendMessage

      security:
        - BearerAuth: []
      
      requestBody:
        description:  |
          The message that the user want to send, in the request are present: <br>
          - the content type of the message
          - the content of the message
        content: 
          multipart/form-data:
            schema:
              description:  |
                  The request body contain the content type, the content of the message
                  and the respondTo
              
              type: object
              properties:
                textContent:
                  $ref: "#/components/schemas/Message/properties/textContent"
                photoContent:
                  $ref: "#/components/schemas/Message/properties/photoContent"
                respondTo:
                  $ref: "#/components/schemas/Message/properties/respondTo"

      
      responses:
        "201":
          description: Message sent succesfully
          content:
            applicatio/json:
              schema:
                description:  |
                  The message just sended
                
                type: object
                properties:
                  message:
                    $ref: "#/components/schemas/Message"
              
              example:
                message:
                  msgId: 999
                  senderId: "ofnarc754"
                  respondTo: -1
                  textContent: "Ciao franco, come stai?"
                  photoContent: ""
                  deliveryStatus: "sent"
                  timestamp: "2021-06-01T14:10:27Z"
                  comments: []

        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"
  
  /chats/{chat_id}/messages/{msg_id}:                             #Endpoint di un messaggio di una chat
    parameters:
      - $ref: "#/components/parameters/chat_id"
      - $ref: "#/components/parameters/msg_id"
    
    delete:
      description: Delete a specific message from the chat by it msg_id.
      summary: Delete a message

      tags: ["Message operation"]
      operationId: deleteMessage

      security:
        - BearerAuth: []

      responses:
        "202":
          description: Message deleted successfully

        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

    put:
      description:  |
        Update the delivery status of a message for an user to read
      summary: Update message status

      tags: ["Message operation"]
      operationId: setMessageStatusToRead

      security:
        - BearerAuth: []

      responses:
        "202":
          description: Message status updated to read correctly

        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

    post:
      description:  |
        Forward a message to the chat that its id is passed in the query in the value "forward_to_chat"
      summary: Forward a message

      tags: ["Message operation"]
      operationId: forwardMessage

      security:
        - BearerAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              description:  |
                The request body want the id of the chat that the message is forwarded to
              type: object
              properties:
                chatToForward:
                  $ref: "#/components/schemas/Chat/properties/chatId"

            example:
              chatToForward: 4
      
      responses:
        "204":
          description: Message forwarded correctly
        
        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

  /chats/{chat_id}/messages/{msg_id}/comments:                    #Endpoint dei commenti di un messaggio
    parameters:
      - $ref: "#/components/parameters/chat_id"
      - $ref: "#/components/parameters/msg_id"
    
    get:
      description:  |
        Retrive the comments of a message
      summary: Get comments for the message

      tags: ["Message operation"]
      operationId: getMessageComments

      security:
        - BearerAuth: []
      
      responses:
        "200":
          description:  |
            Comments retrived successfully

          content:
            application/json:
              schema:
                description:  |
                  Array of comments
                
                type: object
                properties:
                  comments:
                    description:  |
                      maxium number of comment is 16

                    type: array
                    items:
                      $ref: "#/components/schemas/Comment"
                    
                    minItems: 0
                    maxItems: 16
              
              example:
                comments:
                  - commenterId: "ofnarc754"
                    content: "😊"
                  - commenterId: "ordigro293"
                    content: "😒"

        "204":
          description: No comments for the message

        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"
    
    post:
      description:  |
        Comment a message in the chat, the user is identified by the auth token.
      summary: Comment message

      tags: ["Message operation"]
      operationId: commentMessage

      security:
        - BearerAuth: []
      
      requestBody:
        description:  |
          The comment of the user
        
        content: 
          application/json:
            schema:
              description: Content of the comment
              type: object

              properties:
                content:
                  $ref: "#/components/schemas/Comment/properties/content"
        
      responses:
        "202":
          description: Message commented succesfully
        
        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"

  /chats/{chat_id}/messages/{msg_id}/comments/{comment_id}:     #Endpoint di un commento di un messaggio
    parameters:
      - $ref: "#/components/parameters/chat_id"
      - $ref: "#/components/parameters/msg_id"
      - name: comment_id
        in: path
        required: true
        schema:
          type: integer
          readOnly: true
          minimum: 1
          maximum: 32
        description:  |
          Id of the user that made the comment

    delete:
      description:  |
        Remove the comment from a message, by the commenterId
      summary: Uncomment a message

      tags: ["Message operation"]
      operationId: uncommentMessage

      security:
        - BearerAuth: []
      
      responses:
        "204":
          description: Message uncommented succesfully

        "400":
          $ref: "#/components/responses/BadRequestError"

        "401":
          $ref: "#/components/responses/UnauthorizedError"

        "403":
          $ref: "#/components/responses/OperationNotAllowed"

        "404":
          $ref: "#/components/responses/NotFoundError"

        "500":
          $ref: "#/components/responses/InternalError"